variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: secret

test:
  image: node:latest
  services:
    - mysql:5
  script:
    - cd server && npm install && rm node_modules/bcryptjs/src/bower.json && cd tests && npm test usersdaoTest.js